const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const SOURCE_DIR = path.join(REPO_ROOT, 'сеты');
const PUBLIC_DIR = path.join(REPO_ROOT, 'public', 'сеты');
const MANIFEST_PATH = path.join(REPO_ROOT, 'src', 'config', 'generatedSetsImageMap.js');
const SUPPORTED_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif']);

function normalizeSetImageName(value) {
  if (typeof value !== 'string') return '';

  return value
    .toLowerCase()
    .replace(/\.[^.]+$/u, '')
    .replace(/ё/g, 'е')
    .replace(/-/g, ' ')
    .replace(/^сет\s+/u, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function toPublicUrl(fileName) {
  return `/сеты/${encodeURIComponent(fileName)}`;
}

function ensureDirectoryExists(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function readSourceFiles() {
  if (!fs.existsSync(SOURCE_DIR)) {
    throw new Error(`Папка-источник не найдена: ${SOURCE_DIR}`);
  }

  return fs.readdirSync(SOURCE_DIR, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((fileName) => SUPPORTED_EXTENSIONS.has(path.extname(fileName).toLowerCase()))
    .sort((left, right) => left.localeCompare(right, 'ru'));
}

function buildManifest(fileNames) {
  const manifest = {};
  const collisions = [];

  for (const fileName of fileNames) {
    const normalizedName = normalizeSetImageName(fileName);
    if (!normalizedName) continue;

    if (manifest[normalizedName] && manifest[normalizedName] !== toPublicUrl(fileName)) {
      collisions.push({
        normalizedName,
        first: manifest[normalizedName],
        second: toPublicUrl(fileName),
      });
      continue;
    }

    manifest[normalizedName] = toPublicUrl(fileName);
  }

  if (collisions.length > 0) {
    const details = collisions
      .map((collision) => `${collision.normalizedName}: ${collision.first} vs ${collision.second}`)
      .join('\n');

    throw new Error(`Обнаружены конфликтующие изображения сетов после нормализации:\n${details}`);
  }

  return Object.fromEntries(
    Object.entries(manifest).sort(([left], [right]) => left.localeCompare(right, 'ru'))
  );
}

function copyImages(fileNames) {
  ensureDirectoryExists(PUBLIC_DIR);

  for (const fileName of fileNames) {
    const sourcePath = path.join(SOURCE_DIR, fileName);
    const targetPath = path.join(PUBLIC_DIR, fileName);

    fs.copyFileSync(sourcePath, targetPath);
  }
}

function writeManifest(manifest) {
  const fileContents = `// This file is auto-generated by scripts/syncSetsImages.js.\n// Do not edit manually.\n\nexport const SETS_IMAGE_MAP = ${JSON.stringify(manifest, null, 2)};\n`;
  fs.writeFileSync(MANIFEST_PATH, fileContents, 'utf8');
}

function main() {
  const fileNames = readSourceFiles();
  const manifest = buildManifest(fileNames);

  copyImages(fileNames);
  writeManifest(manifest);

  console.log(`sync:sets-images -> synced ${fileNames.length} files and generated ${Object.keys(manifest).length} mappings`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
